# Taskfile.yml
version: "3"

vars:
  # The Docker image to use for all commands.
  TERRAGRUNT_IMAGE: "devopsinfra/docker-terragrunt:ot-1.10.3-tg-0.83.2"

  # All commands will be relative to this path.
  BASE_DIR: "infrastructure-live/provider_aws/dev"
  DOCKER_INTERACTIVE_FLAGS: ""

tasks:
  # ---------------------------------------------------------------------------
  # Core Docker Execution Task (Internal)
  # ---------------------------------------------------------------------------
  # This is a hidden helper task that wraps the docker run command.
  # All other tasks will call this one.
  _run:
    internal: true
    cmds:
      - |
        docker run \
          {{.DOCKER_INTERACTIVE_FLAGS}} \
          --env AWS_REGION \
          --env AWS_DEFAULT_REGION \
          --env AWS_ACCESS_KEY_ID \
          --env AWS_SECRET_ACCESS_KEY \
          --env AWS_SESSION_TOKEN \
          --env HELM_CACHE_HOME=/tmp/helm \
          --user $(id -u):$(id -g) \
          --volume {{.USER_WORKING_DIR}}:/data \
          --workdir /data \
          --rm {{.TERRAGRUNT_IMAGE}} \
          sh -c "{{.CLI_ARGS}}"

  # ---------------------------------------------------------------------------
  # Terragrunt Commands (User-Facing)
  # ---------------------------------------------------------------------------
  # These are the tasks you will run from your command line.

  fmt:
    desc: "Checks formatting for all Terragrunt and Terraform files."
    dir: "{{.BASE_DIR}}"
    cmds:
      - task: _run
        vars:
          CLI_ARGS: "terragrunt hcl format --all && tofu fmt -recursive -check ./infrastructure-modules"

  validate:
    desc: "Initializes and validates all modules."
    dir: "{{.BASE_DIR}}"
    cmds:
      - task: _run
        vars:
          CLI_ARGS: "terragrunt run-all init -reconfigure && terragrunt run-all validate"

  plan:
    desc: "Generates an execution plan for all modules."
    dir: "{{.BASE_DIR}}"
    cmds:
      - task: _run
        vars:
          CLI_ARGS: "terragrunt run-all plan"

  apply:
    desc: "Applies the changes for all modules."
    dir: "{{.BASE_DIR}}"
    cmds:
      - echo "You are about to apply changes to the live infrastructure."
      - task: _run
        vars:
          CLI_ARGS: "terragrunt run-all apply --auto-approve"

  # ---------------------------------------------------------------------------
  # Utility Task
  # ---------------------------------------------------------------------------
  shell:
    desc: "Starts an interactive shell inside the Terragrunt container."
    dir: "{{.BASE_DIR}}"
    cmds:
      - task: _run
        vars:
          DOCKER_INTERACTIVE_FLAGS: "--tty --interactive"
          CLI_ARGS: "bash"
