# .github/workflows/ci.yml
name: "Infra as code CI/CD"

# Run this workflow on every push and pull request
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  format:
    name: "Format & Lint"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: Install Go Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: "Run Format Check via Taskfile"
        run: task fmt
